'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class BangDiem
    Public Property MaHocSinh As String
    Public Property MaMonHoc As String
    Public Property DiemSo As Double

    Public Overridable Property HocSinh As HocSinh
    Public Overridable Property MonHoc As MonHoc

End Class
