'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class LopHoc
    Public Property MaLopHoc As String
    Public Property TenLopHoc As String
    Public Property MaKhoiLop As String

    Public Overridable Property HocSinhs As ICollection(Of HocSinh) = New HashSet(Of HocSinh)
    Public Overridable Property KhoiLop As KhoiLop

End Class
