'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Data.Entity
Imports System.Data.Entity.Infrastructure

Partial Public Class CSDLTRUONGHOCEntities
    Inherits DbContext

    Public Sub New()
        MyBase.New("name=CSDLTRUONGHOCEntities")
    End Sub

    Protected Overrides Sub OnModelCreating(modelBuilder As DbModelBuilder)
        Throw New UnintentionalCodeFirstException()
    End Sub

    Public Overridable Property BangDiems() As DbSet(Of BangDiem)
    Public Overridable Property HocSinhs() As DbSet(Of HocSinh)
    Public Overridable Property KhoiLops() As DbSet(Of KhoiLop)
    Public Overridable Property LopHocs() As DbSet(Of LopHoc)
    Public Overridable Property MonHocs() As DbSet(Of MonHoc)
    Public Overridable Property sysdiagrams() As DbSet(Of sysdiagram)

End Class
