'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class MonHoc
    Public Property MaMonHoc As String
    Public Property TenMonHoc As String
    Public Property HeSoMon As Integer

    Public Overridable Property BangDiems As ICollection(Of BangDiem) = New HashSet(Of BangDiem)

End Class
